// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function createSupabaseAdminClient() {
  const SUPABASE_URL = process.env.SUPABASE_URL;
  const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;
  // All RLS policies are USING(true) with full GRANT to anon, so the publishable
  // key works identically to the service role key for this family app.
  const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL) {
    const message = 'Missing Supabase environment variable: SUPABASE_URL';
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  const authKey = SUPABASE_SERVICE_ROLE_KEY || SUPABASE_PUBLISHABLE_KEY;

  if (!authKey) {
    const message = 'Missing Supabase key: set SUPABASE_SERVICE_ROLE_KEY or SUPABASE_PUBLISHABLE_KEY';
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  if (!SUPABASE_SERVICE_ROLE_KEY) {
    console.warn('[Supabase] SUPABASE_SERVICE_ROLE_KEY not set — falling back to anon key (works with open RLS)');
  }

  return createClient<Database>(SUPABASE_URL, authKey, {
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    }
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Load inside server handlers: const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
// Top-level import is safe only in other .server.ts modules - route files and *.functions.ts ship to the client bundle.
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
